export const nameLookups = [
  {
    A: 'Peanut butter',
    B: 'Toilet',
    C: 'The terorising',
    D: 'ZeepZoop',
    E: 'Fluffy',
    F: 'Wee-Wee',
    G: 'The singing',
    H: 'Heavy',
    I: 'muscle maniac',
    J: 'Jeffory',
    K: 'The dancing',
    L: 'Slippery',
    M: 'Farty',
    N: 'Glitter',
    O: 'Obnoxious',
    P: 'Number two',
    Q: 'Queen',
    R: 'Ravenous',
    S: 'Poo-poo',
    T: 'Bin',
    U: 'Trashy',
    V: 'Chamberpot',
    W: 'The little',
    X: 'Xylophone',
    Y: 'Yellow',
    Z: 'Cheese',
  },
  {
    A: 'Toilet',
    B: 'Junky',
    C: 'Confusing',
    D: 'Earing',
    E: 'Rocket',
    F: 'Fridge',
    G: 'Chipmunk',
    H: 'Alien',
    I: 'Rat',
    J: 'Fish breath',
    K: 'Weird',
    L: 'Old lady',
    M: 'Moonbeam',
    N: 'Ice cream',
    O: 'Stupid',
    P: 'Squirrel',
    Q: 'Guffy',
    R: 'Magic',
    S: 'Pancake',
    T: 'Waffle',
    U: 'Evil',
    V: 'TinkleTrousers',
    W: 'Cornflakes',
    X: 'Chiken',
    Y: 'Dummy',
    Z: 'Crunchy',
  },

  {
    A: 'Sunshine',
    B: 'Magician',
    C: 'Fanny',
    D: 'Lawyer',
    E: 'Fart',
    F: 'Smartypants',
    G: 'Magic',
    H: 'Scientist',
    I: 'Tractor',
    J: 'Junk',
    K: 'Shine',
    L: 'Window',
    M: 'Egg',
    N: 'Chip',
    O: 'Fish',
    P: 'Doritoes',
    Q: 'Spice',
    R: 'Pepper',
    S: 'Salt',
    T: 'Toilet',
    U: 'Shard',
    V: 'Gamer',
    W: 'Hurricane',
    X: 'Person',
    Y: 'Bag',
    Z: 'Cat',
  },
];
